GET http://localhost:4213/xscrapper
# Content-Type: application/json


# POST http://localhost:4213/xscrapper
# Content-Type: application/json

# {
#     "username":"official_ipo_mantra"
# }

# https://api.telegram.org/bot<BotToken>/account.checkUsername

# jeffreybenzhelpbot



# GET  https://t.me/ekete28
# Content-Type: application/json

# {
#     "username":"@BrokeDoomer"
# }